trigger:
  - main
  
pool:
  name: WindowsVMSS

variables:
- group: MagnetForensics-Github

steps:
- checkout: self
  clean: true
  lfs: true
  fetchDepth: 0
  path: s

- checkout: git://Griffeye/pipelines
  displayName: 'Checkout pipelines'
  clean: true
- powershell: pipelines/SetupAgent.ps1 -nugetConfigPath $(Build.SourcesDirectory)\NuGet.Config
  displayName: 'Setup nuget credentials'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- task: PowerShell@2
  displayName: 'Build and test'
  inputs:
    filePath: build.ps1

- task: PublishTestResults@2
  inputs:
    searchFolder: 'test-results'
    testResultsFiles: '*.trx'
    testResultsFormat: VSTest

- task: PublishPipelineArtifact@1
  displayName: 'Publish NuGet Package artifacts'
  inputs:
    targetPath: 'artifacts'
    artifact: 'NuGet'

- task: NuGetCommand@2
  displayName: "Nuget Push to Azure Feed"
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  inputs:
    command: 'push'
    packagesToPush: 'artifacts\*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Griffeye/Library'
    allowPackageConflicts: true # --skip-duplicate

- task: PowerShell@2
  displayName: 'Push to GitHub'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  inputs:
    targetType: 'inline'
    script: |
      git config user.email "Azure@Bot.com"
      git config user.name "AzureDevOpsBot"
      git remote remove github
      git remote add github "https://$(PAT)@github.com/MagnetForensics/griffeye-vlc-wrapper.git"
      git push --force github HEAD:master
  env:
    PAT: $(PAT)