trigger:
  - master
  
pool:
  name: WindowsVMSS

variables:
- group: NuGetPushCredentials
- group: MagnetForensics-Github

steps:
- checkout: git://Griffeye/pipelines
- powershell: pipelines/SetupAgent.ps1

- checkout: self
  clean: true
  lfs: true
  fetchDepth: 0
  path: s # Checkout in source root folder, not a subfolder

- task: PowerShell@2
  displayName: 'Build and test'
  inputs:
    filePath: build.ps1

- task: PublishTestResults@2
  inputs:
    searchFolder: 'test-results'
    testResultsFiles: '*.trx'
    testResultsFormat: VSTest

- task: PublishPipelineArtifact@1
  displayName: 'Publish NuGet Package artifacts'
  inputs:
    targetPath: 'artifacts'
    artifact: 'NuGet'

- powershell: dotnet nuget push artifacts\*.nupkg --skip-duplicate --source $(AnalyzePushSource) --api-key $(AnalyzeApiKey)
  displayName: 'Push NuGet package'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))       

- task: PowerShell@2
  displayName: 'Push to GitHub'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  inputs:
    targetType: 'inline'
    script: |
      git config user.email "Azure@Bot.com"
      git config user.name "AzureDevOpsBot"
      git remote remove github
      git remote add github "https://$(PAT)@github.com/MagnetForensics/griffeye-vlc-wrapper.git"
      git push --force github HEAD:master
  env:
    PAT: $(PAT)